name: SmartCart
version: 0.2.0
description: A minecart transportation plugin!
authors: [floored1585, Seanboyy]
load: startup
main: net.f85.smartcart.SmartCart
commands:
        sc:
                permission: op
                description: SmartCart Control
        scSetTag:
                permission: true
                description: SmartCart set cart tag
